### ISSUE TITLE
Thought This Video Might Be Interesting To You

### ISSUE THREAD

**Issue by Dalayeth** [DouglasDwyer/octo-release#13]
I saw your most recent video and thought this video might be of interest to you

https://www.youtube.com/watch?v=gsZiJeaMO48

You talked about how you were only doing a Monte Carlo integration on only 1 random sample and it still looks great but if you were interested in other techniques I do recommend this video. It talks about both importance sampling and ReSTIR and links papers for using ReSTIR for both direct and indirect lighting.

**Comment by DouglasDwyer** [comment]
Awesome, I'll definitely take a look! I mainly focused on 1 sample/1 bounce for performance reasons, but having true multi-bounce global illumination would be amazing.
