### ISSUE TITLE
window.devicePixelRatio is not considered when setting the canvas size

### ISSUE THREAD

**Issue by Gbr22** [DouglasDwyer/octo-release#5]
![image](https://user-images.githubusercontent.com/25722827/215348271-d4e996c3-bbb4-42d9-bf1a-35b5024c0a55.png)

`window.devicePixelRatio` is not considered when setting the canvas size leading to the canvas only filling a portion of the screen

You should be able to fix it by multiplying the width and height of the canvas with `window.devicePixelRatio`

**Comment by DouglasDwyer** [comment]
Thank you for opening this issue and letting me know! I will be sure to fix this in the next update.

**Comment by DouglasDwyer** [comment]
This issue has been fixed and will be included when the demo is next updated. I appreciate you bringing this to my attention :)
