### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by niels747** [DouglasDwyer/octo-release#6]
I don't know what i'm doing wrong, but this is after loading for a few minutes:
Pressing any keys or moving the mouse doesn't do anything. 
![image](https://user-images.githubusercontent.com/42830240/216346015-65ccb080-af4e-4219-af90-acd44e703848.png)

Browser: Chrome
OS: windows 10

My laptop: 
Intel core i7 6500u
intel HD 520
8GB DDR4

Thank you

**Comment by DouglasDwyer** [comment]
The demo is working, it's just not quite as user-friendly as it could be :)

To get into the game and play, you need to press "t" to lock the mouse, as stated in the top-right corner. I've had multiple people with the same problem, so I probably should make this requirement clearer. I hope that clears things up - feel free to reopen if that doesn't work.
