### ISSUE TITLE
Web demo doesnt even start.

### ISSUE THREAD

**Issue by JulianWogersien** [DouglasDwyer/octo-release#9]
![Screenshot_20240331_160852](https://github.com/DouglasDwyer/octo-release/assets/31437161/2f5bfcea-b6bd-4ec5-8fec-ac69bf65f3e4)

Im using firefox on linux and since i saw on the other open issue that you asked for webgl report here is mine
![Screenshot_20240331_161109](https://github.com/DouglasDwyer/octo-release/assets/31437161/d228c2dc-1799-42d9-8eb6-5aca0dac8689)

![Screenshot_20240331_161130](https://github.com/DouglasDwyer/octo-release/assets/31437161/6b478476-6f04-4053-81d5-ad3a48fbbe03)

![Screenshot_20240331_161138](https://github.com/DouglasDwyer/octo-release/assets/31437161/3ade4752-6d03-4fb0-a2fa-f31e05c8060c)

My gpu currently is a rx 5700 but im upgrading to a 7900xtx soon
I would try native but you only provided a version for windows so i cant

**Comment by DouglasDwyer** [comment]
Thank you very much for the report! The web demo now uses WebGPU, which is only supported on Windows/Mac with Chrome/Edge/Opera as the browser. You can enable WebGPU on Linux with Firefox nightly if you want to try it, but it's not supported on stable yet :)

I could definitely improve my documentation regarding which browsers are supported. I'm going to close this ticket, and update the README to clearly state which platforms the engine supports. I appreciate your interest in the project!
